"""Add first_payment_at to User

Revision ID: de2d669e75d7
Revises: 05253a5c6681
Create Date: 2025-08-29 14:25:47.844069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2d669e75d7'
down_revision: Union[str, Sequence[str], None] = '05253a5c6681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_payment_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_payment_at')
    # ### end Alembic commands ###
